name: Python application

# This workflow will be triggered on push and pull requests to the 'main' and 'dev' branches
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use (e.g., 3.x)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up environment variables using GitHub Secrets
      - name: Set up environment variables
        env:
          USERNAME: ${{ secrets.USERNAME }}
          REPO: ${{ secrets.REPO }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      # Step 5: Run the unit tests
      - name: Run tests
        run: |
          python -m unittest discover -s tests