name: Python application

# This workflow will be triggered on push and pull requests to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use (e.g., 3.x)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up GitHub Secrets (GitHub username, repository, and token)
    - name: Set up GitHub Secrets
      run: |
        echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "REPO=${{ secrets.REPO }}" >> $GITHUB_ENV
        echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
        env:
          USERNAME="DadaNanjesha"
          REPO="GitHub-issue-creator"
          TOKEN=${{ secrets.GITHUB_TOKEN }}
        
       

    # Step 5: Run the unit tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests

