name: Python application

# This workflow will be triggered on push and pull requests to the 'main' and 'dev' branches

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you want to use (e.g., 3.x)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up environment variables using GitHub Secrets
      - name: Set up environment variables and Run tests
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract repository name from github.repository
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "REPO=$REPO" >> $GITHUB_ENV

      # Step 5: Debug environment variables
      - name: Debug environment variables
        run: |
          echo "USERNAME: $USERNAME"
          echo "REPO: $REPO"
          echo "TOKEN: $TOKEN"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upload dependencies as artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-deps
          path: ~/.cache/pip
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Download dependencies artifact
        uses: actions/download-artifact@v2
        with:
          name: python-deps
          path: ~/.cache/pip

      - name: Run tests
        run: |
          python -m unittest discover -s tests
